ManagerCV.Solution/ManagerCV/Pages/CancellaSede.cshtml.cs
using ManagerCVAPI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class CancellaSedeModel : PageModel
    {
        [BindProperty]
        public Sede Sede { get; set; } = default!;
        private static readonly HttpClient client = new()
        {
            BaseAddress = new Uri("https://localhost:7036")
        };
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || await client.GetFromJsonAsync<List<Sede>>($"api/Sedi/{id}") == null)
            {
                return NotFound();
            }

            var sede = await client.GetFromJsonAsync<List<Sede>>($"api/Sedi/{id}");
            if (sede == null)
            {
                return NotFound();
            }
            Sede = sede[0];
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (Sede == null)
            {
                return NotFound();
            }
            await client.DeleteAsync($"api/Sedi/{Sede.Id}");
            return RedirectToPage("/ElencoSedi");
        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/CreaSede.cshtml.cs
using ManagerCVAPI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class CreaSedeModel : PageModel
    {
        [BindProperty]
        public Sede Sede { get; set; } = default!;
        private static HttpClient client = new()
        {
            BaseAddress = new Uri("https://localhost:7036")
        };
        private string uri = "api/Sedi";
        public IActionResult OnGet()
        {
            return Page();
        }
        public async Task<IActionResult> OnPostAsync ()
        {
            if (!ModelState.IsValid || Sede == null)
            {
                return Page();
            }
            await client.PostAsJsonAsync<Sede>(uri, Sede);
            return RedirectToPage("/ElencoSedi");
        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/ElencoSedi.cshtml.cs
using ManagerCVAPI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class ElencoSediModel : PageModel
    {
        [BindProperty]
        public int? Ricerca { get; set; }
        public List<Sede> ListaSedi { get; set; }
        private static readonly HttpClient client = new()
        {
            BaseAddress = new Uri("https://localhost:7036")
        };
        private readonly string uri = "api/Sedi";
        public ElencoSediModel()
        {
            ListaSedi = new List<Sede>();
        }
        public async Task<IActionResult> OnGet()
        {
            List<Sede>? sediDaApi = await client.GetFromJsonAsync<List<Sede>>(uri);
            ListaSedi = sediDaApi!;
            return Page();
        }
        public async Task<IActionResult> OnPostById()
        {
            List<Sede>? sediDaApi = await client.GetFromJsonAsync<List<Sede>>($"api/Sedi/{Ricerca}");
            ListaSedi = sediDaApi!;
            return Page();
        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ManagerCV.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/ModificaSede.cshtml.cs
using ManagerCVAPI.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class ModificaSedeModel : PageModel
    {
        [BindProperty]
        public Sede Sede { get; set; } = default!;
        private static HttpClient client = new()
        {
            BaseAddress = new Uri("https://localhost:7036")
        };
        private string uri = "api/Sedi";
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sede = await client.GetFromJsonAsync<List<Sede>>($"api/Sedi/{id}");
            
            if (sede == null)
            {
                return NotFound();
            }
            Sede = sede[0];
            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                await client.PutAsJsonAsync<Sede>(uri, Sede);
                return RedirectToPage("/ElencoSedi");
            }
        }

    }
}

ManagerCV.Solution/ManagerCV/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManagerCV.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ManagerCV.Solution/ManagerCV/Pages/CancellaSede.cshtml
@page
@model ManagerCV.Pages.CancellaSedeModel
@{
}
<h1>Elimina la sede di @($"{Model.Sede.Città}")</h1>

<h3>Sei sicuro di voler proseguire? Quest'azione è irreversibile.</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.Città)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.Città)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.Indirizzo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.Indirizzo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.Provincia)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.Provincia)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.Cap)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.Cap)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.RecapitoTel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.RecapitoTel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sede.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sede.Email)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Sede.Id" />
        <input type="submit" value="Elimina" class="btn btn-danger" /> |
        <a asp-page="./ElencoSedi" class="btn btn-primary">Torna alla Lista</a>
    </form>
</div>

ManagerCV.Solution/ManagerCV/Pages/CreaSede.cshtml
@page
@model ManagerCV.Pages.CreaSedeModel
@{
}
<h1>Inserisci una nuova Sede</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sede.Città" class="control-label"></label>
                <input asp-for="Sede.Città" class="form-control" />
                <span asp-validation-for="Sede.Città" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Indirizzo" class="control-label"></label>
                <input asp-for="Sede.Indirizzo" class="form-control" />
                <span asp-validation-for="Sede.Indirizzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Provincia" class="control-label"></label>
                <input asp-for="Sede.Provincia" class="form-control" />
                <span asp-validation-for="Sede.Provincia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Cap" class="control-label"></label>
                <input asp-for="Sede.Cap" class="form-control" />
                <span asp-validation-for="Sede.Cap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Recapito Telefonico</label>
                <input asp-for="Sede.RecapitoTel" class="form-control" />
                <span asp-validation-for="Sede.RecapitoTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Email" class="control-label"></label>
                <input asp-for="Sede.Email" class="form-control" />
                <span asp-validation-for="Sede.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Invia" class="btn btn-warning" />
                <a asp-page="ElencoSedi" class="btn btn-primary mb-2 mt-2">Torna alla Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ManagerCV.Solution/ManagerCV/Pages/ElencoSedi.cshtml
@page
@model ManagerCV.Pages.ElencoSediModel
@{

}
<div class="container">
    <form method="post" class="d-flex mb-2" asp-page-handler="ById">
        <div class="input-group">
            <input class="form-control col-md-4 me-2" type="number" asp-for="Ricerca">
        </div>
        <div>
            <button class="btn btn-primary ms-2" type="submit">Cerca</button>
        </div>
    </form>
</div>
<table class="table table-bordered table-custom table-responsive md-3">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Indirizzo</th>
            <th scope="col">Città</th>
            <th scope="col">Provincia</th>
            <th scope="col">Cap</th>
            <th scope="col">Recapito Telefonico</th>
            <th scope="col">Mail</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model.ListaSedi)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Indirizzo</td>
                    <td>@item.Città</td>
                    <td>@item.Provincia</td>
                    <td>@item.Cap</td>
                    <td>@item.RecapitoTel</td>
                    <td>@item.Email</td>
                    <td><a asp-page="./ModificaSede" asp-route-id="@item.Id" class="btn btn-warning ms-2">Modifica</a></td>
                    <td><a asp-page="./CancellaSede" asp-route-id="@item.Id" class="btn btn-danger ms-2">Elimina</a></td>
                </tr>
            }
        }
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <a asp-page="CreaSede" class="btn btn-primary ">Inserisci una Nuova Sede</a>
</div>

ManagerCV.Solution/ManagerCV/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ManagerCV.Solution/ManagerCV/Pages/ModificaSede.cshtml
@page
@model ManagerCV.Pages.ModificaSedeModel
@{
}

<h1>Modifica la sede di @($"{Model.Sede.Città}")</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Sede.Id" />
            <div class="form-group">
                <label asp-for="Sede.Città" class="control-label"></label>
                <input asp-for="Sede.Città" class="form-control" />
                <span asp-validation-for="Sede.Città" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Indirizzo" class="control-label"></label>
                <input asp-for="Sede.Indirizzo" class="form-control" />
                <span asp-validation-for="Sede.Indirizzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Provincia" class="control-label"></label>
                <input asp-for="Sede.Provincia" class="form-control" />
                <span asp-validation-for="Sede.Provincia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Cap" class="control-label"></label>
                <input asp-for="Sede.Cap" class="form-control" />
                <span asp-validation-for="Sede.Cap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Recapito Telefonico</label>
                <input asp-for="Sede.RecapitoTel" class="form-control" />
                <span asp-validation-for="Sede.RecapitoTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sede.Email" class="control-label"></label>
                <input asp-for="Sede.Email" class="form-control" />
                <span asp-validation-for="Sede.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salva" class="btn btn-primary mt-2" />
                <a asp-page="./ElencoSedi" class="btn btn-primary mt-3 mb-2">Torna alla Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}